import type { Database } from './database.generated';

export type CategoryInsert    = Database['public']['Tables']['categories']['Insert'];
export type CategoryUpdate    = Database['public']['Tables']['categories']['Update'];
export type Category      = Database['public']['Tables']['categories']['Row'];
export type TagInsert         = Database['public']['Tables']['tags']['Insert'];
export type TagUpdate         = Database['public']['Tables']['tags']['Update'];
export type Tag           = Database['public']['Tables']['tags']['Row'];
export type IdeaInsert        = Database['public']['Tables']['ideas']['Insert'];
export type IdeaUpdate        = Database['public']['Tables']['ideas']['Update'];
export type Idea          = Database['public']['Tables']['ideas']['Row'];
export type ProjectInsert     = Database['public']['Tables']['projects']['Insert'];
export type ProjectUpdate     = Database['public']['Tables']['projects']['Update'];
export type Project       = Database['public']['Tables']['projects']['Row'];
export type GoalInsert        = Database['public']['Tables']['goals']['Insert'];
export type GoalUpdate        = Database['public']['Tables']['goals']['Update'];
export type Goal          = Database['public']['Tables']['goals']['Row'];
export type TaskInsert        = Database['public']['Tables']['tasks']['Insert'];
export type TaskUpdate        = Database['public']['Tables']['tasks']['Update'];
export type Task          = Database['public']['Tables']['tasks']['Row'];
export type CalendarEventInsert = Database['public']['Tables']['calendar_events']['Insert'];
export type CalendarEventUpdate = Database['public']['Tables']['calendar_events']['Update'];
export type CalendarEvent = Database['public']['Tables']['calendar_events']['Row'];
