import type { Database } from './database.generated';

export type IdeaInsert        = Database['public']['Tables']['ideas']['Insert'];
export type IdeaUpdate        = Database['public']['Tables']['ideas']['Update'];
export type Idea          = Database['public']['Tables']['ideas']['Row'];
export type ProjectInsert     = Database['public']['Tables']['projects']['Insert'];
export type ProjectUpdate     = Database['public']['Tables']['projects']['Update'];
export type Project       = Database['public']['Tables']['projects']['Row'];
export type GoalInsert        = Database['public']['Tables']['goals']['Insert'];
export type GoalUpdate        = Database['public']['Tables']['goals']['Update'];
export type Goal          = Database['public']['Tables']['goals']['Row'];
export type TaskInsert        = Database['public']['Tables']['tasks']['Insert'];
export type TaskUpdate        = Database['public']['Tables']['tasks']['Update'];
export type Task          = Database['public']['Tables']['tasks']['Row'];
export type IdeaExpansionInsert = Database['public']['Tables']['idea_expansions']['Insert'];
export type IdeaExpansion       = Database['public']['Tables']['idea_expansions']['Row'];
export type ProjectPlanInsert   = Database['public']['Tables']['project_plans']['Insert'];
export type ProjectPlan         = Database['public']['Tables']['project_plans']['Row'];
export type MorningBriefLogInsert = Database['public']['Tables']['morning_brief_log']['Insert'];
export type MorningBriefLogUpdate = Database['public']['Tables']['morning_brief_log']['Update'];
export type MorningBriefLog       = Database['public']['Tables']['morning_brief_log']['Row'];
